[theme]
primaryColor = "#F63366"
backgroundColor = "#E7E7E7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[server]
enableXsrfProtection = false
enableCORS = false
port = 5000
baseUrlPath = ""
headless = true