[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "Heebo"

[server]
enableXsrfProtection = false
enableCORS = false
port = 5000
baseUrlPath = ""
headless = true