[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E7E7E7"
textColor = "#262730"
font = "sans serif"

[server]
enableXsrfProtection = false
enableCORS = false
port = 5000
baseUrlPath = ""
headless = true

[browser]
gatherUsageStats = false
